# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run..
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

   # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         sudo rm -rf /tmp/test/*
         sudo mv /home/ubuntu/actions-runner/_work/test/test/* /tmp/test
      - name: Notify Slack
        uses: drilonrecica/action-slack-notify@0.0.3
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://upload.wikimedia.org/wikipedia/commons/6/68/NoxttonBot.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: drilonrecica
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}  
